### PR TITLE
feature: external mode.

### LINKED ISSUE #32: if it possible to extract data provider out of component?
I use MQTT to get log line by line, it's not websocket nor http.

it would be nice if the api look like:

```typescript

interface LazyLogController {
  newLine(lines:[]string) => void
  end() => void
  start() => void
  error() => void
}

const ref = userRef<LazyLogController>()

useEffect(() => {
   ref.current?.start()
   ref.current?.newLines(['test1','test2'])
   // ...
}, [])

<LazyLog ref={ref} follow>

```

### PR DESCRIPTION
**Pull request by JokerQyou**
Fix #32 Add external mode in which log lines are appended by parent component.

### CODE REVIEW

**Comment by melloware** [comment]
awesome can you add a new StoryBook demo showing this behavior for external control.  Its pretty easy to add StoryBook. For example like this one: https://melloware.github.io/react-logviewer/?path=/story/stories-lazylog--clear-method you could have a button that just appends a new random line of text?

Also can you make sure this scenario is not broken: https://melloware.github.io/react-logviewer/?path=/story/stories-lazylog--highlight-and-scrolling  I saw you changed the scrollToLine stuff.

**Comment by JokerQyou** [comment]
Sure, I'll check storybook tomorrow.

**Comment by melloware** [comment]
you rock!  Right after this is done i will push a new release to NPM.

**Comment by JokerQyou** [comment]
I've added story for external mode. As for the `scrollToLine` stuff, I did not see the scroll story break. I initially thought it was a typo in the original code, since a function named `scrollToIndex` would normally expect an `index` variable rather than a `line`. If it's not the case, comment and I'll revert that line.

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
6.1.0 is on NPM

**Pull request merged**
